// Serve robots.txt at /robots.txt with explicit AI crawler tier policy.
// Search/agent-grounding bots allowed; training-only crawlers disallowed.
// Cloudflare Content Signals draft included as a structured purpose declaration.
export default defineEventHandler((event) => {
  setResponseHeader(event, 'Content-Type', 'text/plain; charset=utf-8')
  setResponseHeader(event, 'Cache-Control', 'public, max-age=3600')

  const lines: string[] = [
    '# robots.txt for cake47.art (snowcake47 illustration portfolio)',
    '# Spec: https://www.robotstxt.org/',
    '# AI crawler taxonomy follows the agent-readiness conventions used by orank/Cloudflare.',
    '',
    '# Default policy — open for indexing, exclude private admin surface.',
    'User-agent: *',
    'Allow: /',
    'Disallow: /admin',
    'Disallow: /api/admin/',
    '',
    '# --- AI search & agent grounding (allowed) ---',
    'User-agent: ChatGPT-User',
    'Allow: /',
    '',
    'User-agent: OAI-SearchBot',
    'Allow: /',
    '',
    'User-agent: ClaudeBot',
    'Allow: /',
    '',
    'User-agent: Claude-Web',
    'Allow: /',
    '',
    'User-agent: Claude-User',
    'Allow: /',
    '',
    'User-agent: PerplexityBot',
    'Allow: /',
    '',
    'User-agent: Perplexity-User',
    'Allow: /',
    '',
    'User-agent: Google-Extended',
    'Allow: /',
    '',
    'User-agent: Applebot-Extended',
    'Allow: /',
    '',
    'User-agent: ora-agent',
    'Allow: /',
    '',
    '# --- AI training-only crawlers (not allowed) ---',
    'User-agent: GPTBot',
    'Disallow: /',
    '',
    'User-agent: CCBot',
    'Disallow: /',
    '',
    'User-agent: Bytespider',
    'Disallow: /',
    '',
    'User-agent: Google-CloudVertexBot',
    'Disallow: /',
    '',
    'User-agent: Meta-ExternalAgent',
    'Disallow: /',
    '',
    'User-agent: anthropic-ai',
    'Disallow: /',
    '',
    'User-agent: cohere-ai',
    'Disallow: /',
    '',
    '# --- Content Signals (Cloudflare draft) ---',
    '# Declares purpose-based permissions independent of user-agent identity.',
    'Content-Signal: search=yes, ai-input=yes, ai-train=no',
    '',
    'Sitemap: https://cake47.art/sitemap.xml',
    'Schemamap: https://cake47.art/schemamap.xml',
  ]

  return `${lines.join('\n')}\n`
})
